# Generated by Django 5.0 on 2023-12-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_alter_clinic_review'),
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='review',
        ),
        migrations.AddField(
            model_name='clinic',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_app.review'),
        ),
    ]
