# Generated by Django 5.0 on 2023-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_clinic_specialists'),
        ('review_app', '0004_remove_review_author_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='review_app.review'),
        ),
    ]
