# Generated by Django 5.0 on 2023-12-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0007_alter_clinic_reviews'),
        ('review_app', '0004_remove_review_author_review_author'),
        ('specialist_app', '0005_alter_specialist_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='specialists',
        ),
        migrations.AddField(
            model_name='clinic',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_app.review'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='specialists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialist_app.specialist'),
        ),
    ]
