# Generated by Django 5.0 on 2023-12-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_remove_clinic_specialists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='reviews',
        ),
    ]
