# Generated by Django 5.0 on 2023-12-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_patient_is_active_patient_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
