# Generated by Django 5.0 on 2023-12-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('THERAPIST', 'Therapist'), ('SURGEON', 'Surgeon'), ('PEDIATRICIAN', 'Pediatrician'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('NEUROLOGIST', 'Neurologist'), ('DENTIST', 'Dentist'), ('ONCOLOGIST', 'Oncologist')], max_length=20)),
                ('experience', models.IntegerField(max_length=2)),
                ('price', models.CharField(max_length=7)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.clinic')),
            ],
        ),
    ]
