# Generated by Django 5.0 on 2023-12-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality', models.CharField(choices=[('Therapist', 'Therapist'), ('Surgeon', 'Surgeon'), ('Pediatrician', 'Pediatrician'), ('Ophthalmologist', 'Ophthalmologist'), ('Neurologist', 'Neurologist'), ('Dentist', 'Dentist'), ('Oncologist', 'Oncologist')], max_length=20)),
                ('experience', models.IntegerField(blank=True, max_length=2, null=True)),
                ('price', models.CharField(max_length=7)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='clinic_app.clinic')),
            ],
        ),
    ]
