# Generated by Django 5.0 on 2023-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_app', '0002_remove_specialist_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
