# Generated by Django 5.0 on 2023-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_app', '0004_alter_specialist_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='speciality',
            field=models.CharField(choices=[('Therapist', 'Therapist'), ('Surgeon', 'Surgeon'), ('Pediatrician', 'Pediatrician'), ('Ophthalmologist', 'Ophthalmologist'), ('Neurologist', 'Neurologist'), ('Dentist', 'Dentist'), ('Oncologist', 'Oncologist')], max_length=20),
        ),
    ]
