# Generated by Django 5.0 on 2023-12-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_remove_clinic_specialists'),
        ('specialist_app', '0006_specialist_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='clinic_app.clinic'),
        ),
    ]
