# Generated by Django 5.0 on 2023-12-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0002_alter_record_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='patient',
        ),
    ]
