# Generated by Django 5.0 on 2023-12-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0005_alter_record_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
    ]
