# Generated by Django 5.0 on 2023-12-13 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_remove_clinic_reviews'),
        ('review_app', '0004_remove_review_author_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='clinic_app.clinic'),
        ),
    ]
