# Generated by Django 5.0 on 2023-12-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_remove_clinic_reviews'),
        ('review_app', '0008_alter_review_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.clinic'),
        ),
    ]
